FROM alpine:3.10

ENV RUBY_VERSION 2.6.3
ENV RUBY_INSTALL_PACKAGE 0.7.0

# update packages and install required packages
RUN apk --no-cache add build-base \
                       linux-headers \ 
                       libressl-dev \
                       zlib-dev \
                       bash
#ruby install
WORKDIR /ruby-install
RUN wget -O ruby-install-${RUBY_INSTALL_PACKAGE}.tar.gz https://github.com/postmodern/ruby-install/archive/v${RUBY_INSTALL_PACKAGE}.tar.gz \
    && tar -xzvf ruby-install-${RUBY_INSTALL_PACKAGE}.tar.gz \
    && cd /ruby-install/ruby-install-${RUBY_INSTALL_PACKAGE}/ \
    && make install && ruby-install --system ruby ${RUBY_VERSION} \
    && cd / \
    && rm -rf /ruby-install \
    && gem install bundler && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem \
    && ruby -v
